version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.30.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.19.0
    volumes:
      - ./blackbox_exporter:/config
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - "9115:9115"

  grafana:
    image: grafana/grafana:8.2.5
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DATASOURCES_DEFAULT_NAME=Prometheus
      - DS_SIGNCL_PROMETHEUS=Prometheus
    ports:
      - "3000:3000"

  alertmanager:
    image: prom/alertmanager:v0.23.0
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

